#!/bin/bash

feh --bg-scale /home/gambo/wp.jpg
#xcompmgr & 
#dte(){
#	dte=$(date)
#	echo -e " $(dte)"
#
#}

#cpu() {
#	read cpu a b c previdle rest < /proc/stat
#	prevtotal=$((a+b+c+previdle))
#	read cpu a b c idle rest < /proc/stat
#	total=$((a+b+c+idle))
#	cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
#	echo -e " $cpu% cpu"
#}

while true; do
	xsetroot -name "$(/home/gambo/.scripts/dte)"
	sleep 1s
xcompmgr & 
done & 













exec dwm

