#!/bin/bash

feh --bg-scale /home/gambo/Downloads/7137245.png
xcompmgr & 

while true; do
	xsetroot -name "$(/home/gambo/.scripts/dte)"
	sleep 1s
done & 

export AWK_TOOLKIT=MToolkit & 

#If you're using vmware uncomment below line for open-vm-tools to work
#/usr/bin/vmware-user-suid-wrapper & 

exec dwm

